---
id: ruby-snap-docker-2018
base_name: ruby-snap-docker-2018
tags:
- ruby
presentation_date: 2018/12/01
version: 2018.12.01
licenses: []
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :markdown
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
